### ISSUE TITLE
Not know how to run setup.sh

### ISSUE THREAD

**Issue by QayyumMustaqim** [amanchadha/coursera-deep-learning-specialization#11]
Anyone can guide me how to run setup.sh?

**Comment by scorpiusprime** [comment]
same issue here

**Comment by amanchadha** [comment]
`chmod +x setup.sh
./setup.sh`

**Comment by scorpiusprime** [comment]
> `chmod +x setup.sh`
> `./setup.sh`

I tried this, did not work. instead I opened the setup.sh file in sublime and there was a weblink : https://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat

opening this link in browser started a download, I hope it is downloading the data I am looking for.
