### ISSUE TITLE
C2 - Week 1 - PA 2 - Regularization - data.mat

### ISSUE THREAD

**Issue by BJBijvoet** [amanchadha/coursera-deep-learning-specialization#25]
I cannot manage to download the dataset `data.mat` for C2 - PA2. This is the link to the file in this GitHub:
https://github.com/amanchadha/coursera-deep-learning-specialization/blob/6ebc4d60a90c1592aee3eaa3113eb4b37d9b4b19/C2%20-%20Improving%20Deep%20Neural%20Networks%20Hyperparameter%20tuning,%20Regularization%20and%20Optimization/Week%201/Regularization/datasets/data.mat
Can anybody share a download link to a file, e.g., via OneDrive, Google Drive, or any other similar service? 

Much appreciated!

**Comment by BJBijvoet** [comment]
Solved, found it here: https://github.com/cruzcid/Improving-Deep-Neural-Networks---Hyperparameter-tuning-Regularization-and-Optimization/tree/master/Regularization%20-%20Assignment%202

**Comment by kevin-weitgenant** [comment]
thanks
